//! Pure History retention policy for the encrypted state snapshot.
//!
//! This module owns no files and performs no commits. The acceptance owner
//! supplies entries from an already-authenticated snapshot and persists the
//! resulting collection atomically with its other state.
//!
//! Production command/capability wiring remains intentionally open until
//! Task 20 provides the atomic acceptance and encrypted snapshot owner.

use std::{collections::HashSet, fmt, time::Duration};

use serde::{Deserialize, Serialize};

use crate::clock::Timestamp;

use super::{crypto::keyed_digest, StateKey};

/// Maximum number of durable History records.
pub const HISTORY_CAPACITY: usize = 50;

/// The only History retention choices exposed by the product.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(try_from = "u8", into = "u8")]
pub enum HistoryRetention {
    /// Do not retain Detected OTPs in durable History.
    Off,
    /// Retain entries for one day.
    OneDay,
    /// Retain entries for seven days. This is the product default.
    #[default]
    SevenDays,
    /// Retain entries for thirty days.
    ThirtyDays,
}

/// A raw persistence value did not represent an approved retention choice.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InvalidHistoryRetention;

impl fmt::Display for InvalidHistoryRetention {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("History retention must be Off, 1, 7, or 30 days")
    }
}

impl std::error::Error for InvalidHistoryRetention {}

impl TryFrom<u8> for HistoryRetention {
    type Error = InvalidHistoryRetention;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::Off),
            1 => Ok(Self::OneDay),
            7 => Ok(Self::SevenDays),
            30 => Ok(Self::ThirtyDays),
            _ => Err(InvalidHistoryRetention),
        }
    }
}

impl From<HistoryRetention> for u8 {
    fn from(value: HistoryRetention) -> Self {
        match value {
            HistoryRetention::Off => 0,
            HistoryRetention::OneDay => 1,
            HistoryRetention::SevenDays => 7,
            HistoryRetention::ThirtyDays => 30,
        }
    }
}

impl HistoryRetention {
    /// Returns the duration for an enabled choice.
    pub fn duration(self) -> Option<Duration> {
        match self {
            Self::Off => None,
            Self::OneDay => Some(Duration::from_secs(24 * 60 * 60)),
            Self::SevenDays => Some(Duration::from_secs(7 * 24 * 60 * 60)),
            Self::ThirtyDays => Some(Duration::from_secs(30 * 24 * 60 * 60)),
        }
    }
}

/// An opaque durable History identifier.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize)]
#[serde(transparent)]
pub struct HistoryEntryId(String);

impl HistoryEntryId {
    /// Wraps a non-empty identifier generated by the acceptance owner.
    pub fn new(value: impl Into<String>) -> Result<Self, InvalidHistoryEntry> {
        let value = value.into();
        if value.trim().is_empty() {
            return Err(InvalidHistoryEntry::EmptyHistoryId);
        }
        Ok(Self(value))
    }

    /// Returns the opaque value for a delete request or durable snapshot.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Derives the opaque durable identifier for one accepted source Message.
    ///
    /// The derivation is deterministic so a redelivered Message maps to the
    /// same record, and keyed so it reveals nothing about the source.
    pub fn derive(key: &StateKey, source: &SourceMessageDigest) -> Self {
        Self(hex::encode(keyed_digest(
            key,
            b"otpbar-history-entry-id-v1",
            source.as_str().as_bytes(),
        )))
    }
}

/// Opaque source-Message identity used for Recent Code uniqueness.
#[derive(Clone, PartialEq, Eq, Hash, Serialize)]
#[serde(transparent)]
pub struct SourceMessageDigest(String);

impl SourceMessageDigest {
    /// Wraps a canonical lowercase hexadecimal HMAC-SHA-256 digest generated
    /// by the acceptance owner.
    pub fn new(value: impl Into<String>) -> Result<Self, InvalidHistoryEntry> {
        let value = value.into();
        if value.len() != 64
            || !value
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        {
            return Err(InvalidHistoryEntry::InvalidSourceMessageDigest);
        }
        Ok(Self(value))
    }

    /// Returns the opaque source identity for projection deduplication.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for SourceMessageDigest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("SourceMessageDigest([redacted])")
    }
}

/// Display and normalized key for the Provider of a Detected OTP.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct HistoryProvider {
    key: String,
    display: String,
}

impl HistoryProvider {
    /// Creates a Provider representation suitable for durable History.
    pub fn new(
        key: impl Into<String>,
        display: impl Into<String>,
    ) -> Result<Self, InvalidHistoryEntry> {
        let key = key.into();
        let display = display.into();
        if key.trim().is_empty() {
            return Err(InvalidHistoryEntry::EmptyProviderKey);
        }
        if display.trim().is_empty() {
            return Err(InvalidHistoryEntry::EmptyProviderDisplay);
        }
        Ok(Self { key, display })
    }

    /// Returns the normalized Provider key used by settings and matching.
    pub fn key(&self) -> &str {
        &self.key
    }

    /// Returns the Provider label shown to the user.
    pub fn display(&self) -> &str {
        &self.display
    }
}

/// One durable Detected OTP record in History.
#[derive(Clone, PartialEq, Eq, Serialize)]
pub struct HistoryEntry {
    id: HistoryEntryId,
    code: String,
    message_origin_display: String,
    provider: HistoryProvider,
    received_at: Timestamp,
    source_message_digest: SourceMessageDigest,
}

impl fmt::Debug for HistoryEntry {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("HistoryEntry")
            .field("id", &self.id)
            .field("code", &"[redacted]")
            .field("message_origin_display", &self.message_origin_display)
            .field("provider", &self.provider)
            .field("received_at", &self.received_at)
            .field("source_message_digest", &self.source_message_digest)
            .finish()
    }
}

impl HistoryEntry {
    /// Creates a validated durable History record.
    pub fn new(
        id: HistoryEntryId,
        code: impl Into<String>,
        message_origin_display: impl Into<String>,
        provider: HistoryProvider,
        received_at: Timestamp,
        source_message_digest: SourceMessageDigest,
    ) -> Result<Self, InvalidHistoryEntry> {
        let code = code.into();
        let message_origin_display = message_origin_display.into();
        if code.trim().is_empty() {
            return Err(InvalidHistoryEntry::EmptyCode);
        }
        if message_origin_display.trim().is_empty() {
            return Err(InvalidHistoryEntry::EmptyMessageOrigin);
        }
        Ok(Self {
            id,
            code,
            message_origin_display,
            provider,
            received_at,
            source_message_digest,
        })
    }

    /// Returns this entry's opaque durable identifier.
    pub fn id(&self) -> &HistoryEntryId {
        &self.id
    }

    /// Returns the Detected OTP value.
    pub fn code(&self) -> &str {
        &self.code
    }

    /// Returns the human-readable Message Origin.
    pub fn message_origin_display(&self) -> &str {
        &self.message_origin_display
    }

    /// Returns the associated Provider.
    pub fn provider(&self) -> &HistoryProvider {
        &self.provider
    }

    /// Returns the Message receipt time.
    pub const fn received_at(&self) -> Timestamp {
        self.received_at
    }

    /// Returns the opaque source Message identity.
    pub fn source_message_digest(&self) -> &SourceMessageDigest {
        &self.source_message_digest
    }
}

/// A History record was structurally incomplete.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InvalidHistoryEntry {
    EmptyHistoryId,
    InvalidSourceMessageDigest,
    EmptyProviderKey,
    EmptyProviderDisplay,
    EmptyCode,
    EmptyMessageOrigin,
}

impl fmt::Display for InvalidHistoryEntry {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::EmptyHistoryId => "History entry ID cannot be empty",
            Self::InvalidSourceMessageDigest => {
                "source Message digest must be 64 lowercase hexadecimal characters"
            }
            Self::EmptyProviderKey => "Provider key cannot be empty",
            Self::EmptyProviderDisplay => "Provider display cannot be empty",
            Self::EmptyCode => "Detected OTP cannot be empty",
            Self::EmptyMessageOrigin => "Message Origin cannot be empty",
        })
    }
}

impl std::error::Error for InvalidHistoryEntry {}

/// Pure durable History policy and its normalized records.
#[derive(Clone, PartialEq, Eq)]
pub struct History {
    retention: HistoryRetention,
    entries: Vec<HistoryEntry>,
}

impl fmt::Debug for History {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("History")
            .field("retention", &self.retention)
            .field("entries", &self.entries)
            .finish()
    }
}

impl History {
    /// Restores persisted entries, dropping expired records and enforcing the cap.
    pub fn restore(
        retention: HistoryRetention,
        entries: impl IntoIterator<Item = HistoryEntry>,
        now: Timestamp,
    ) -> Self {
        let mut history = Self {
            retention,
            entries: entries.into_iter().collect(),
        };
        history.normalize(now);
        history
    }

    /// Returns the current validated retention policy.
    pub const fn retention(&self) -> HistoryRetention {
        self.retention
    }

    /// Returns newest-first durable records.
    pub fn entries(&self) -> &[HistoryEntry] {
        &self.entries
    }

    /// Adds or replaces one record when durable retention is enabled.
    ///
    /// The return value reports whether the record is present afterward. An
    /// expired record and every record under History Off are deliberately not
    /// retained.
    pub fn record(&mut self, entry: HistoryEntry, now: Timestamp) -> bool {
        self.normalize(now);
        if self.retention == HistoryRetention::Off || !self.is_unexpired(&entry, now) {
            return false;
        }
        let expected = entry.clone();
        self.entries.push(entry);
        self.normalize(now);
        self.entries.contains(&expected)
    }

    /// Removes one durable record by its opaque identifier.
    pub fn delete(&mut self, id: &HistoryEntryId) -> bool {
        let original_len = self.entries.len();
        self.entries.retain(|entry| entry.id != *id);
        self.entries.len() != original_len
    }

    /// Removes every durable record.
    pub fn clear(&mut self) {
        self.entries.clear();
    }

    /// Applies a new policy immediately, including the required Off deletion.
    pub fn set_retention(&mut self, retention: HistoryRetention, now: Timestamp) {
        self.retention = retention;
        self.normalize(now);
    }

    /// Drops entries that have expired since the prior policy operation.
    pub fn prune_expired(&mut self, now: Timestamp) {
        self.normalize(now);
    }

    fn normalize(&mut self, now: Timestamp) {
        if self.retention == HistoryRetention::Off {
            self.entries.clear();
            return;
        }
        let retention = self.retention;
        self.entries
            .retain(|entry| is_unexpired(retention, entry, now));
        self.entries.sort_by(|left, right| {
            right
                .received_at
                .cmp(&left.received_at)
                .then_with(|| left.id.as_str().cmp(right.id.as_str()))
        });
        let mut seen_sources = HashSet::new();
        let mut seen_ids = HashSet::new();
        self.entries.retain(|entry| {
            seen_sources.insert(entry.source_message_digest.clone())
                && seen_ids.insert(entry.id.clone())
        });
        self.entries.truncate(HISTORY_CAPACITY);
    }

    fn is_unexpired(&self, entry: &HistoryEntry, now: Timestamp) -> bool {
        is_unexpired(self.retention, entry, now)
    }
}

fn is_unexpired(retention: HistoryRetention, entry: &HistoryEntry, now: Timestamp) -> bool {
    let Some(duration) = retention.duration() else {
        return false;
    };
    entry
        .received_at
        .checked_add(duration)
        .is_none_or(|expires_at| now < expires_at)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::clock::Timestamp;
    use std::time::Duration;

    fn entry(id: &str, source: &str, received_at: i64) -> HistoryEntry {
        let source = format!("{:0<64}", hex::encode(source));
        HistoryEntry::new(
            HistoryEntryId::new(id).expect("opaque history id"),
            "123456",
            "Example message origin",
            HistoryProvider::new("example", "Example").expect("provider"),
            Timestamp::from_unix_millis(received_at),
            SourceMessageDigest::new(source).expect("canonical source identity"),
        )
        .expect("valid entry")
    }

    #[test]
    fn retention_is_defaulted_and_validated_at_the_policy_boundary() {
        assert_eq!(HistoryRetention::default(), HistoryRetention::SevenDays);
        assert_eq!(HistoryRetention::try_from(0), Ok(HistoryRetention::Off));
        assert_eq!(HistoryRetention::try_from(1), Ok(HistoryRetention::OneDay));
        assert_eq!(
            HistoryRetention::try_from(7),
            Ok(HistoryRetention::SevenDays)
        );
        assert_eq!(
            HistoryRetention::try_from(30),
            Ok(HistoryRetention::ThirtyDays)
        );
        assert_eq!(HistoryRetention::try_from(2), Err(InvalidHistoryRetention));
        assert_eq!(HistoryRetention::Off.duration(), None);
        assert_eq!(
            HistoryRetention::OneDay.duration(),
            Some(Duration::from_secs(24 * 60 * 60))
        );
    }

    #[test]
    fn history_keeps_only_unexpired_entries_up_to_its_durable_cap() {
        let now = Timestamp::from_unix_millis(30 * 24 * 60 * 60 * 1_000);
        let entries: Vec<_> = (0..55)
            .map(|index| {
                entry(
                    &format!("history-{index}"),
                    &format!("source-{index}"),
                    now.unix_millis() - index,
                )
            })
            .chain(std::iter::once(entry(
                "expired",
                "expired-source",
                now.unix_millis() - 31 * 24 * 60 * 60 * 1_000,
            )))
            .collect();

        let history = History::restore(HistoryRetention::ThirtyDays, entries, now);

        assert_eq!(history.entries().len(), 50);
        assert_eq!(history.entries()[0].id().as_str(), "history-0");
        assert_eq!(history.entries()[49].id().as_str(), "history-49");
    }

    #[test]
    fn retention_off_erases_durable_history_and_rejects_new_records() {
        let now = Timestamp::from_unix_millis(10 * 24 * 60 * 60 * 1_000);
        let persisted = entry("persisted", "source-persisted", now.unix_millis());
        let arrival = entry("arrival", "source-arrival", now.unix_millis());
        let mut history = History::restore(HistoryRetention::SevenDays, [persisted], now);

        history.set_retention(HistoryRetention::Off, now);

        assert!(history.entries().is_empty());
        assert!(!history.record(arrival, now));
        assert!(history.entries().is_empty());
    }

    #[test]
    fn each_enabled_retention_expires_at_its_exact_boundary() {
        let now = Timestamp::from_unix_millis(40 * 24 * 60 * 60 * 1_000);
        for (retention, duration) in [
            (HistoryRetention::OneDay, Duration::from_secs(24 * 60 * 60)),
            (
                HistoryRetention::SevenDays,
                Duration::from_secs(7 * 24 * 60 * 60),
            ),
            (
                HistoryRetention::ThirtyDays,
                Duration::from_secs(30 * 24 * 60 * 60),
            ),
        ] {
            let received_at = now
                .checked_add(Duration::ZERO)
                .and_then(|timestamp| timestamp.checked_add(duration))
                .map(|timestamp| {
                    Timestamp::from_unix_millis(
                        now.unix_millis() - (timestamp.unix_millis() - now.unix_millis()),
                    )
                })
                .expect("representable fixture");
            let history = History::restore(
                retention,
                [entry(
                    "boundary",
                    "boundary-source",
                    received_at.unix_millis(),
                )],
                now,
            );

            assert!(
                history.entries().is_empty(),
                "{retention:?} boundary must expire"
            );
        }
    }

    #[test]
    fn delete_one_and_clear_remove_only_the_requested_durable_records() {
        let now = Timestamp::from_unix_millis(10 * 24 * 60 * 60 * 1_000);
        let first = entry("first", "source-first", now.unix_millis());
        let second = entry("second", "source-second", now.unix_millis() - 1);
        let first_id = first.id().clone();
        let mut history = History::restore(HistoryRetention::SevenDays, [first, second], now);

        assert!(history.delete(&first_id));
        assert_eq!(history.entries().len(), 1);
        assert!(!history.delete(&first_id));
        history.clear();
        assert!(history.entries().is_empty());
    }

    #[test]
    fn restore_and_record_keep_only_the_newest_entry_for_each_source_message() {
        let now = Timestamp::from_unix_millis(10 * 24 * 60 * 60 * 1_000);
        let older = entry("older", "same-source", now.unix_millis() - 10);
        let newer = entry("newer", "same-source", now.unix_millis() - 5);
        let mut history = History::restore(HistoryRetention::SevenDays, [older, newer], now);

        assert_eq!(history.entries().len(), 1);
        assert_eq!(history.entries()[0].id().as_str(), "newer");

        assert!(history.record(entry("newest", "same-source", now.unix_millis()), now));
        assert_eq!(history.entries().len(), 1);
        assert_eq!(history.entries()[0].id().as_str(), "newest");

        assert!(!history.record(entry("stale", "same-source", now.unix_millis() - 20), now));
        assert_eq!(history.entries().len(), 1);
        assert_eq!(history.entries()[0].id().as_str(), "newest");
    }

    #[test]
    fn debug_output_redacts_detected_otp_values() {
        let now = Timestamp::from_unix_millis(10 * 24 * 60 * 60 * 1_000);
        let history = History::restore(
            HistoryRetention::SevenDays,
            [entry("history", "source", now.unix_millis())],
            now,
        );

        assert!(!format!("{history:?}").contains("123456"));
        assert!(format!("{history:?}").contains("[redacted]"));
    }

    #[test]
    fn clock_rollback_and_unrepresentable_expiry_do_not_delete_history() {
        let future = entry("future", "future-source", 10_000);
        let rollback_history = History::restore(
            HistoryRetention::OneDay,
            [future],
            Timestamp::from_unix_millis(1),
        );
        assert_eq!(rollback_history.entries().len(), 1);

        let boundary = entry("boundary", "boundary-source", i64::MAX);
        let boundary_history = History::restore(
            HistoryRetention::ThirtyDays,
            [boundary],
            Timestamp::from_unix_millis(i64::MAX),
        );
        assert_eq!(boundary_history.entries().len(), 1);
    }

    #[test]
    fn derived_entry_ids_are_deterministic_keyed_and_source_unique() {
        let key = StateKey::from_bytes(&[7u8; 32]).expect("256-bit key");
        let other_key = StateKey::from_bytes(&[9u8; 32]).expect("256-bit key");
        let source = SourceMessageDigest::new("ab".repeat(32)).expect("canonical digest");
        let other_source = SourceMessageDigest::new("cd".repeat(32)).expect("canonical digest");

        let id = HistoryEntryId::derive(&key, &source);

        assert_eq!(id, HistoryEntryId::derive(&key, &source));
        assert_ne!(id, HistoryEntryId::derive(&key, &other_source));
        assert_ne!(id, HistoryEntryId::derive(&other_key, &source));
        assert!(!id.as_str().is_empty());
    }

    #[test]
    fn source_message_digest_requires_canonical_lowercase_hmac_shape_and_redacts_debug() {
        let canonical = "ab".repeat(32);
        let digest = SourceMessageDigest::new(canonical.clone()).expect("canonical digest");

        assert_eq!(digest.as_str(), canonical);
        assert_eq!(
            SourceMessageDigest::new("ab"),
            Err(InvalidHistoryEntry::InvalidSourceMessageDigest)
        );
        assert_eq!(
            SourceMessageDigest::new("AB".repeat(32)),
            Err(InvalidHistoryEntry::InvalidSourceMessageDigest)
        );
        assert!(!format!("{digest:?}").contains(&canonical));
        assert!(format!("{digest:?}").contains("[redacted]"));
    }
}
