//! Payload-free metadata for automatic effects.

use std::{collections::HashSet, fmt, time::Duration};

use serde::{Deserialize, Deserializer, Serialize};
use sha2::{Digest, Sha256};

use crate::clock::Timestamp;

/// Pending/claimed metadata is useful only while its current-process payload exists.
pub const LIVE_INTENT_RETENTION: Duration = Duration::from_secs(5 * 60);
/// Terminal metadata is retained briefly for diagnostics and deduplication.
pub const EFFECT_TOMBSTONE_RETENTION: Duration = Duration::from_secs(24 * 60 * 60);
/// Hard bound for durable effect metadata.
pub const EFFECT_OUTBOX_CAPACITY: usize = 512;

/// Opaque automatic-effect identity generated by the acceptance owner.
#[derive(Clone, PartialEq, Eq, Hash, Serialize)]
#[serde(transparent)]
pub struct EffectIntentId(String);

impl EffectIntentId {
    /// Validates a fixed 256-bit lowercase-hex opaque intent identity.
    fn new(value: impl Into<String>) -> Result<Self, InvalidEffectIntent> {
        let value = value.into();
        if value.len() != 64
            || !value
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        {
            return Err(InvalidEffectIntent::InvalidId);
        }
        Ok(Self(value))
    }

    /// Returns the opaque durable identifier.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Debug for EffectIntentId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("EffectIntentId([redacted])")
    }
}

impl<'de> Deserialize<'de> for EffectIntentId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        Self::new(String::deserialize(deserializer)?).map_err(serde::de::Error::custom)
    }
}

/// External automatic operation requested by an acceptance.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EffectKind {
    AutoCopy,
    Notification,
}

impl EffectIntentId {
    /// Derives a domain-separated opaque identity from an already-keyed Seen
    /// Message identity. Callers never supply durable effect IDs.
    pub(crate) fn derive(seen_identity: &str, kind: EffectKind) -> Self {
        let mut digest = Sha256::new();
        digest.update(b"otpbar-effect-intent-id-v1");
        digest.update(seen_identity.as_bytes());
        digest.update(match kind {
            EffectKind::AutoCopy => b"auto_copy".as_slice(),
            EffectKind::Notification => b"notification".as_slice(),
        });
        Self(hex::encode(digest.finalize()))
    }
}

/// Durable lifecycle state. Execution is owned by the current process only.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EffectState {
    Pending,
    Claimed,
    Completed,
    Canceled,
    Expired,
}

/// Fixed, redacted terminal result metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RedactedEffectOutcome {
    Succeeded,
    Failed,
    RestartedWithoutPayload,
    Expired,
}

/// One durable automatic-effect record. It has no field capable of storing a code.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EffectIntent {
    id: EffectIntentId,
    acceptance_revision: u64,
    provider: String,
    kind: EffectKind,
    state: EffectState,
    created_at: Timestamp,
    updated_at: Timestamp,
    outcome: Option<RedactedEffectOutcome>,
}

impl EffectIntent {
    pub fn id(&self) -> &EffectIntentId {
        &self.id
    }

    pub const fn acceptance_revision(&self) -> u64 {
        self.acceptance_revision
    }

    pub fn provider(&self) -> &str {
        &self.provider
    }

    pub const fn kind(&self) -> EffectKind {
        self.kind
    }

    pub const fn state(&self) -> EffectState {
        self.state
    }

    pub const fn outcome(&self) -> Option<RedactedEffectOutcome> {
        self.outcome
    }
}

/// Validated durable effect metadata.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize)]
#[serde(transparent)]
pub struct EffectOutbox(Vec<EffectIntent>);

impl<'de> Deserialize<'de> for EffectOutbox {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let intents = Vec::<EffectIntent>::deserialize(deserializer)?;
        if intents.len() > EFFECT_OUTBOX_CAPACITY {
            return Err(serde::de::Error::custom(
                InvalidEffectIntent::CapacityExceeded,
            ));
        }
        let mut ids = HashSet::new();
        for intent in &intents {
            if intent.acceptance_revision == 0 {
                return Err(serde::de::Error::custom(
                    InvalidEffectIntent::InvalidAcceptanceRevision,
                ));
            }
            if intent.provider.trim().is_empty() {
                return Err(serde::de::Error::custom(InvalidEffectIntent::EmptyProvider));
            }
            if !ids.insert(intent.id.clone()) {
                return Err(serde::de::Error::custom(InvalidEffectIntent::DuplicateId));
            }
        }
        Ok(Self(intents))
    }
}

impl EffectOutbox {
    /// Returns durable metadata in stable insertion order.
    pub fn intents(&self) -> &[EffectIntent] {
        &self.0
    }

    /// Returns intents that could be claimed in the current process.
    pub fn live_count(&self) -> usize {
        self.0
            .iter()
            .filter(|intent| matches!(intent.state, EffectState::Pending | EffectState::Claimed))
            .count()
    }

    /// Adds one payload-free pending intent.
    pub fn add_pending(
        &mut self,
        id: EffectIntentId,
        acceptance_revision: u64,
        provider: impl Into<String>,
        kind: EffectKind,
        now: Timestamp,
    ) -> Result<(), InvalidEffectIntent> {
        let provider = provider.into();
        if acceptance_revision == 0 {
            return Err(InvalidEffectIntent::InvalidAcceptanceRevision);
        }
        if provider.trim().is_empty() {
            return Err(InvalidEffectIntent::EmptyProvider);
        }
        if self.0.iter().any(|intent| intent.id == id) {
            return Err(InvalidEffectIntent::DuplicateId);
        }
        if self.0.len() >= EFFECT_OUTBOX_CAPACITY {
            return Err(InvalidEffectIntent::CapacityExceeded);
        }
        self.0.push(EffectIntent {
            id,
            acceptance_revision,
            provider,
            kind,
            state: EffectState::Pending,
            created_at: now,
            updated_at: now,
            outcome: None,
        });
        Ok(())
    }

    /// Claims one pending intent for the current process.
    pub fn claim(&mut self, id: &EffectIntentId, now: Timestamp) -> bool {
        self.expire_and_prune(now);
        let Some(intent) = self
            .0
            .iter_mut()
            .find(|intent| intent.id == *id && intent.state == EffectState::Pending)
        else {
            return false;
        };
        intent.state = EffectState::Claimed;
        intent.updated_at = now;
        true
    }

    /// Records a terminal, redacted result for one current-process claim.
    pub fn complete(
        &mut self,
        id: &EffectIntentId,
        outcome: RedactedEffectOutcome,
        now: Timestamp,
    ) -> bool {
        let Some(intent) = self
            .0
            .iter_mut()
            .find(|intent| intent.id == *id && intent.state == EffectState::Claimed)
        else {
            return false;
        };
        intent.state = EffectState::Completed;
        intent.updated_at = now;
        intent.outcome = Some(outcome);
        true
    }

    /// Cancels every live intent during startup; none is returned for execution.
    pub fn cancel_live_after_restart(&mut self, now: Timestamp) -> usize {
        let mut canceled = 0;
        for intent in &mut self.0 {
            if matches!(intent.state, EffectState::Pending | EffectState::Claimed) {
                intent.state = EffectState::Canceled;
                intent.updated_at = now;
                intent.outcome = Some(RedactedEffectOutcome::RestartedWithoutPayload);
                canceled += 1;
            }
        }
        self.expire_and_prune(now);
        canceled
    }

    /// Expires live metadata after five minutes and prunes 24-hour tombstones.
    pub fn expire_and_prune(&mut self, now: Timestamp) {
        for intent in &mut self.0 {
            if matches!(intent.state, EffectState::Pending | EffectState::Claimed)
                && deadline_reached(intent.created_at, LIVE_INTENT_RETENTION, now)
            {
                intent.state = EffectState::Expired;
                intent.updated_at = now;
                intent.outcome = Some(RedactedEffectOutcome::Expired);
            }
        }
        self.0.retain(|intent| {
            matches!(intent.state, EffectState::Pending | EffectState::Claimed)
                || !deadline_reached(intent.updated_at, EFFECT_TOMBSTONE_RETENTION, now)
        });
    }
}

fn deadline_reached(start: Timestamp, duration: Duration, now: Timestamp) -> bool {
    start
        .checked_add(duration)
        .is_some_and(|deadline| now >= deadline)
}

/// Structurally invalid or unbounded durable effect metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InvalidEffectIntent {
    InvalidId,
    InvalidAcceptanceRevision,
    EmptyProvider,
    DuplicateId,
    CapacityExceeded,
}

impl fmt::Display for InvalidEffectIntent {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::InvalidId => "effect intent identity must be 64 lowercase hexadecimal characters",
            Self::InvalidAcceptanceRevision => "effect acceptance revision must be positive",
            Self::EmptyProvider => "effect Provider cannot be empty",
            Self::DuplicateId => "effect intent identity already exists",
            Self::CapacityExceeded => "effect metadata capacity was reached",
        })
    }
}

impl std::error::Error for InvalidEffectIntent {}

#[cfg(test)]
mod tests {
    use crate::clock::Timestamp;

    use super::{EffectIntentId, EffectKind, EffectOutbox};

    #[test]
    fn otp_shaped_and_arbitrary_intent_ids_are_unrepresentable_and_debug_is_redacted() {
        assert!(EffectIntentId::new("123456").is_err());
        assert!(EffectIntentId::new("intent-1").is_err());
        assert!(serde_json::from_str::<EffectIntentId>("\"123456\"").is_err());
        let id = EffectIntentId::derive(&"a".repeat(64), EffectKind::AutoCopy);
        assert_eq!(format!("{id:?}"), "EffectIntentId([redacted])");
        assert!(!format!("{id:?}").contains(&"a".repeat(64)));
    }

    #[test]
    fn pending_intent_serialization_contains_metadata_but_never_the_otp_payload() {
        let mut outbox = EffectOutbox::default();
        outbox
            .add_pending(
                EffectIntentId::new("a".repeat(64)).unwrap(),
                7,
                "example",
                EffectKind::AutoCopy,
                Timestamp::from_unix_millis(1_000),
            )
            .unwrap();

        let serialized = serde_json::to_string(&outbox).unwrap();
        assert!(serialized.contains(&"a".repeat(64)));
        assert!(serialized.contains("example"));
        assert!(serialized.contains("auto_copy"));
        assert!(!serialized.contains("123456"));
        assert!(!serialized.contains("otp"));
        assert!(!serialized.contains("payload"));
    }

    #[test]
    fn restart_cancels_pending_and_claimed_metadata_without_returning_work_to_execute() {
        let now = Timestamp::from_unix_millis(1_000);
        let mut outbox = EffectOutbox::default();
        let pending = EffectIntentId::new("b".repeat(64)).unwrap();
        let claimed = EffectIntentId::new("c".repeat(64)).unwrap();
        outbox
            .add_pending(pending, 1, "example", EffectKind::Notification, now)
            .unwrap();
        outbox
            .add_pending(claimed.clone(), 1, "example", EffectKind::AutoCopy, now)
            .unwrap();
        assert!(outbox.claim(&claimed, now));

        assert_eq!(
            outbox.cancel_live_after_restart(Timestamp::from_unix_millis(2_000)),
            2
        );
        assert_eq!(outbox.live_count(), 0);
        assert!(outbox
            .intents()
            .iter()
            .all(|intent| intent.state() == super::EffectState::Canceled));
        assert!(outbox.intents().iter().all(|intent| {
            intent.outcome() == Some(super::RedactedEffectOutcome::RestartedWithoutPayload)
        }));
    }

    #[test]
    fn completed_effects_never_become_claimable_again_and_live_metadata_expires_at_five_minutes() {
        let created = Timestamp::from_unix_millis(1_000);
        let mut outbox = EffectOutbox::default();
        let completed = EffectIntentId::new("d".repeat(64)).unwrap();
        let expires = EffectIntentId::new("e".repeat(64)).unwrap();
        outbox
            .add_pending(
                completed.clone(),
                1,
                "example",
                EffectKind::AutoCopy,
                created,
            )
            .unwrap();
        outbox
            .add_pending(expires, 1, "example", EffectKind::Notification, created)
            .unwrap();
        assert!(outbox.claim(&completed, created));
        assert!(outbox.complete(&completed, super::RedactedEffectOutcome::Succeeded, created));

        outbox.expire_and_prune(Timestamp::from_unix_millis(301_000));
        assert!(!outbox.claim(&completed, Timestamp::from_unix_millis(301_000)));
        assert_eq!(outbox.live_count(), 0);
        assert!(outbox
            .intents()
            .iter()
            .any(|intent| intent.state() == super::EffectState::Completed));
        assert!(outbox
            .intents()
            .iter()
            .any(|intent| intent.state() == super::EffectState::Expired));
    }
}
